### ISSUE TITLE
use github actions as ci/cd

### ISSUE THREAD

**Issue by maxheld83** [ropensci/tic#118]
[GitHub actions](http://github.com/features/actions) is a new workflow automation (~ CI/CD) service from GitHub, still in limited beta as of now.
I think it has some potential for R.

I've written a package for quickly getting started with GitHub actions: [ghactions](http://www.maxheld.de/ghactions/).

Would you guys be interested in supporting GitHub actions as a "backend" CI/CD provider?

If so, medium term, I'd like to work on supplying that backend through ghactions (much as the travis pkg currently does for tic).

It's obviously still very early days for github actions and the still maturing ghactions package, so it'll be some time before this makes sense.

Just wanted to raise this here to get your feedback and also to avoid doing duplicate work.

(also tracked in https://github.com/maxheld83/ghactions/issues/56)

**Comment by krlmlr** [comment]
Thanks for reaching out. This looks promising, I've signed up for the beta.

Would the processing of all of `tic.R` occur in a single action?

**Comment by maxheld83** [comment]
I think the more idiomatic way would be to render the `tic.R` into *separate* actions though I guess technically both is possible.
Separate actions would also make it easier to create sensible feedback that's easy to reason about for users.

ghactions currently also does this (= splitting workflows into separate actions) via some pretty rudimentary templating.

I'm going to work full-time on ghactions starting May 1st for a couple of months, and will report back here once I have an idea of how to tie this in with tic.

**Comment by maelle** [comment]
Sorry for the thread hijack but "I'm going to work full-time on ghactions starting May 1st for a couple of months" wow super good news!

**Comment by pat-s** [comment]
Similar to #169, this is a useful CI backend that we should consider supporting (soon) as its out of beta now.

**Comment by maxheld83** [comment]
I have the templating functions in [ghactions](http://maxheld.de/ghactions/) almost ready for prime time; I hope you might find these useful for the backend functions in tic.
There's a function for each of the nested YAML blocks (`step()`, `workflow()` etc.) that lets you write valid YAML.
It also exposes argument names and does some sanity checks.
I'll report back in this issue when it's on CRAN.

**Comment by pat-s** [comment]
Sounds great! Thanks Max!
