### ISSUE TITLE
Rethink argument interface to macros

### ISSUE THREAD

**Issue by krlmlr** [ropensci/tic#151]
I'm not sure the current approach for macro functions is sustainable, or makes them particularly easy to use.

Currently, we're copying over all arguments to the signature of the macro functions. Maybe we should opt for something more like the following:

```
do_package_checks(
  step_install_deps(repos = repo_bioc()),
  step_rcmdcheck(error_on = "note")
)
```

If step definitions are omitted, defaults are used.

Thoughts, @pat-s @maelle @zkamvar?

**Comment by krlmlr** [comment]
Maybe later.

**Comment by pat-s** [comment]
One advantage of the current macro notation is that tic.R is quite tidy.
If we would require writing down all steps again, tic.R would become quite messy.

Let's keep it like it is for now? I'd say it's fine.

Feel free to re-open if you disagree :)
