### ISSUE TITLE
Questions about the Getting started vignette

### ISSUE THREAD

**Issue by maelle** [ropensci/tic#210]
I'm reading the getting started vignette and have a few questions.

* Why "
We recommend the following setup:
● Appveyor: Windows
● Circle CI: Linux
● Travis CI: macOS"? Could there be some footnote about the reason for that?

* Why would someone want to deploy from several CI, do you have a practical example?

* In "The deployment setup functionality comes" I wonder where the _Appveyor_ functionality comes from.

* At the beginning of the vignette your link resources about CI in general but mostly Travis, do you know of some comparisons of all CIs for R packages or so? 

(Maybe I should also read the peer-review thread to see whether there are answers there :wink:)

**Comment by pat-s** [comment]
Thanks for the feedback! 🤗 

> We recommend the following setup:

Currently its like

```
We recommend the following setup:
● Travis CI: Linux
● Travis CI: macOS
● Appveyor: Windows
```

whereas this is debatable and I'd like to use Circle for Linux. I currently do not know why @krlmlr has switched Linux to Travis.
This point will probably always be opinionated and several arguments could be raised in favor of different configurations.

Yes, maybe there should a short justification why our default are the way they are.

> Why would someone want to deploy from several CI, do you have a practical example?

The only practical one I could think of is when building drat binaries for different OS systems. The point here is simply that there is no reason to restrict it from our side to only one provider.

> In "The deployment setup functionality comes" I wonder where the Appveyor functionality comes from.

From [krlmlr/r-appveyor](https://github.com/krlmlr/r-appveyor). Good point, we should add that link.

> At the beginning of the vignette your link resources about CI in general but mostly Travis, do you know of some comparisons of all CIs for R packages or so?

No. The thing is that support for other providers (Circle, Azure, GH actions) is very young/experimental right now and I don't know of any post comparing some/all off them. I wanted to write a post about the advantages of Circle vs Travis but that is still a draft.

If you know of a post that explains why the new kid on the block GH actions is supposed to be so much better than everything else than let me know :smile: (I haven't yet had time to dive in in detail). We want to add backend support for this soon but we also could need more help in the whole project :(

**Comment by maelle** [comment]
Many thanks!

To me a big advantage of GH actions for e.g. lockedata/starters is that if you have a GitHub repo, activating = simply committing and pushing a config file (and we have enough layers in starters 😅). Besides, you can push it to a branch to check things before adding it to master. But no I don't know of a good reference yet!
