### ISSUE TITLE
Support more than one deploy key

### ISSUE THREAD

**Issue by krlmlr** [ropensci/tic#22]
From https://github.com/ropenscilabs/travis/issues/61#issuecomment-310911966:

> This is rather difficult: GitHub doesn't allow using the same deploy key for two repositories, and we can only use one private key on Travis CI without involving an SSH agent. This means that we currently can have either drat or pkgdown/packagedocs, but not both.

Shelved for now.

**Comment by krlmlr** [comment]
Can write `~/.ssh/config` file to support multiple `id_rsa` files: https://stackoverflow.com/a/33228296/946850

**Comment by pat-s** [comment]
Since both _drat_ and _packagedocs_ are kind of niche, should we just live with that restriction for now? I do not see anyone of us investing time into this issue in the near future?
