### ISSUE TITLE
Implicit R version dep R >=3.5

### ISSUE THREAD

**Issue by pat-s** [ropensci/tic#220]
Because in the DESC file we require backports >= 1.1.5. For this version no binary exists for R 3.4 (and currently we allow no source installs on Appveyor due to some annoyances when building pkgs from source there). Subsequently all `install_github(tic)` calls error on R 3.4 stating that backports v1.1.5 is not available.

The requirement does not apply anymore since the actual code which caused it does not exist anymore. See https://github.com/ropensci/tic/pull/183 

I'll just remove the requirement and see no real issue currently why that would be a problem. Do you agree @krlmlr?

We added the requirement because of 

- Added backport for isTRUE() implementing the new behaviour introduced in R 3.5.0.

Example failing build:

https://ci.appveyor.com/project/mlr3learners/mlr3learners-ksvm/builds/30168417/job/hd7twllj758w5kh8

**Comment by pat-s** [comment]
While this worked, the same now happens because of cli v2.0.0 😂

**Comment by krlmlr** [comment]
Does this mean that we require R >= 3.5 for testing on Windows?

**Comment by pat-s** [comment]
Exactly, unless we open up for source installs again on Appveyor.
