### ISSUE TITLE
Why exclamation mark

### ISSUE THREAD

**Issue by maelle** [ropensci/tic#233]
I'm wondering about "by checking the mandatory(!) DESCRIPTION file", why is there an exclamation mark?

**Comment by pat-s** [comment]
Because we wanted to put weight on the fact that a DESCR file is always required, no matter the project type. Is this "too heavy"?

**Comment by maelle** [comment]
aaaah ok. Maybe make that a separate item somewhere else in the README? Right now that item is under "For an R package" but what you want to mention, if I follow correctly, is that all projects should track their dependencies using a DESCRIPTION file? You could mention tools helping set this up (`attachment`, `usethis::use_description()`, `usethis::use_package()`).
