### ISSUE TITLE
Resources about CI?

### ISSUE THREAD

**Issue by maelle** [ropensci/tic#234]
I was reading "Also, there is no way around familiarizing yourself with the basics of CI systems in general." and wondering what a good intro would be. It could be linked from this sentence.

**Comment by pat-s** [comment]
Yeah there could be more links to CI resources, at least to their own "quickstart" docs or similar.

**Comment by maelle** [comment]
that'd be great, otherwise it could be a bit frustrating for beginners "oh this looks cool! ah but where do I start?!". :sweat_smile:

**Comment by pat-s** [comment]
However this will always be the case I guess.

Having a kickstart for CI via {tic} is great but if you do not know whats happening behind the scenes it becomes problematic.
There is no way around reading the docs and going through all the information.

However it is hard for us to catch everyone on the way as people arrive here with lots of different backgrounds. In theory we should catch everyone but we can't re-teach the absolute basics of CI in our docs.

I had lots of discussions about this with related people and - it's complicated 😞

**Comment by maelle** [comment]
Oh I wasn't suggesting that! I was thinking more along the lines of recommending your favourite resources for learning the basics, and saying each service "wrapped" by tic also has a starter guide. And maybe you could throw a few words e.g. "You should more or less know what word1, word2, word3 mean".

**Comment by maelle** [comment]
I suppose it could be "Requirements for using tic and getting the most of it"

* Learn CI basics blablabla.
* Track your project dependencies with a DESCRIPTION file blablabla.

**Comment by maelle** [comment]
And a third item would be

* Be prepared to track changes to this package blablabla (our discussion on a commit).

Every blablabla could be hidden in an html details thing so it wouldn't clutter the README too much?

All of this being suggestions, obviously. :wink:
