### ISSUE TITLE
Error calling `tic::deploy()` locally: 'tic-remote' does not appear to be a git repository

### ISSUE THREAD

**Issue by andrewmaclachlan** [ropensci/tic#243]
Hi there

When i try and run `tic::deploy()` using GitHub Actions for a bookdown project i get:

`fatal: 'tic-remote' does not appear to be a git repository
fatal: Could not read from remote repository.`

First time using CI, so will probably be something obvious!

**Comment by pat-s** [comment]
You usually should not have to call `tic::deploy()` locally, it is designed to be run in CI runs (though you can do it if you want).

However, if you do, you should do it within a git repository or have `tic.R` set up correctly.
