### ISSUE TITLE
Tic generates an incorrect URL for runs

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/tic#245]
This is the URL, generated by `tic` I believe, that is incorrect:

https://github.com/ITSLeeds/od/runs/75967827

See the commit message from the deploy stage that generated it here: https://github.com/ITSLeeds/od/commit/ba9ccd6f46ecf35ae297ae821811846ffc8d8c73

The correct URL is:

https://github.com/ITSLeeds/od/actions/runs/75967827

I think. Guessing this will be a quick fix.

**Comment by Robinlovelace** [comment]
https://github.com/ropensci/tic/blob/41ccd454448eace2df6a4f7e976ddebc1b5f83c0/R/gh-actions.R#L28

**Comment by pat-s** [comment]
Yeah thanks for reporting!
