### ISSUE TITLE
Add Google Cloud Build?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [ropensci/tic#248]
Hi I just found this as I was looking to get Cloud build approved for ropensci/googleLanguageR

I've a package for interfacing with Cloud Build at https://code.markedmondson.me/googleCloudRunner/ which I use for authenticated tests for my Google-API based packages.  

Could it fit in tic too?  If you think its appropriate, I can start looking at a pull request.

**Comment by pat-s** [comment]
Hi Marc,

thanks for the pointer. Haven't head of Google Cloud Build before. Lots of new providers coming up lately.

Sure, if you are motivated and have the time feel free to create a PR. Happy to review it.
The Circle CI setup also runs on rocker and might be the closest one you can stick to. However, the general principle is the same for all providers in {tic}.

I don't have enough capacities to tackle this myself unfortunately. The next big thing in {tic} will be an auto-update functionality for YAML changes which is highly needed.

**Comment by pat-s** [comment]
@MarkEdmondson1234 Any updates?

**Comment by MarkEdmondson1234** [comment]
I will track the issue on googleCloudRunner and close this one to keep it out of your hair. Its just reached 0.2 on CRAN so would like to make sure its running smoothly first and then look at integration with other packages like tic.
