### ISSUE TITLE
About the warning in `InstallDeps$prepare()`

### ISSUE THREAD

**Issue by pat-s** [ropensci/tic#258]
https://github.com/ropensci/tic/blob/33828133e93a55b7b902b6615b685b53ef3cdd0c/R/steps-install.R#L15-L18

I am not sure if this warning is of much help for users:

- It gets printed in every run, even if `step_install_deps()` is used in the correct context
- I am not sure if users can take any (the correct) action if the warning applies in the correct context

I suggest to put this line into `?step_install_pkg` and remove it from `InstallDeps$prepare()`.

@krlmlr

**Comment by krlmlr** [comment]
Agreed.
