### ISSUE TITLE
Cleaning up ropenscilabs

### ISSUE THREAD

**Issue by jeroen** [ropensci/tic#291]
We are trying to clean up the [ropenscilabs](http://github.com/ropenscilabs) organization. The idea is that this organization should mostly be a temporary home for experimental projects. Mature projects should be moved either to `/ropensci` or the maintainer github account. Abandoned projects will eventually get moved to [ropensci-archive](https://github.com/ropensci-archive).

It seems like `tic` depends on many ropensci labs projects:

 - https://github.com/ropenscilabs/travis
 - https://github.com/ropenscilabs/circle
 - https://github.com/ropenscilabs/tic.website
 - https://github.com/ropenscilabs/tic.package
 - https://github.com/ropenscilabs/tic.figshare
 - https://github.com/ropenscilabs/tic.drat.repo
 - https://github.com/ropenscilabs/tic.drat
 - https://github.com/ropenscilabs/tic.covrpage
 - https://github.com/ropenscilabs/tic.bookdown
 - https://github.com/ropenscilabs/tic.blogdown

Are all these projects still active? What would be a good long-term home for these repositories? It almost looks like you need a `tic-org` on github?

**Comment by pat-s** [comment]
{travis} and {circle} should go to ropensci imo. Currently {circle} is in review and I just recently found a way for http testing which seems to work (via {vcr}). Right after {circle}, {travis} should follow.
They are deps of {tic} which should go to CRAN afterwards.

Unfortunately my time is limited so this process goes slowly. Happy to accept help :) 

Related to all the {tic} demo repos: I was never a fan of them and not sure if they are of any help. According to @krlmlr they were asked for when initialising the project.
Note that they are not depends but only "example repos".
I am not sure if moving them to a dedicated repo would make things better (from a dev POV).
I'd rather archive/delete them and keep things tidy and polish the documentation of {tic}.

Let's see what @krlmlr opinion is on this.

**Comment by krlmlr** [comment]
If these repos are required by documentation, we can move them elsewhere. If not, let's archive.

**Comment by pat-s** [comment]
ping @jeroen

**Comment by jeroen** [comment]
I see `travis` is now also eol. Do I understand it correctly that I should archive all of the repositories, except for `circle` ?

**Comment by pat-s** [comment]
In theory yes but I would first want to check for remaining doc references and merge #295 first. Then we could archive (maybe I can even do it myself?) - need to check.

**Comment by pat-s** [comment]
@jeroen Travis funtionality has been removed and all references to the example repos in the README as well. The mentioned repos can be archived.

**Comment by jeroen** [comment]
Thanks for your help in cleaning up ropensci! I have now archived the above repo's.
