### ISSUE TITLE
Travis-CI On MacOS `brew install ccache` fails 

### ISSUE THREAD

**Issue by alexrecuenco** [ropensci/tic#293]
I had some issues with a very old tic installation, and after restarting it form scratch, I notice this step installing ccache and it keeps failing. 

https://travis-ci.org/github/alexrecuenco/TexExamRandomizer/jobs/743329360

I am not sure how to proceed, I've been trying the whole week and I seem to not be able to find a solution, or what went wrong.

**Comment by alexrecuenco** [comment]
It seems to be a brew link failure. Any idea how to fix this? I would rather not modify the template manually to be able to update the template in the future more easily.

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/gfortran
Target /usr/local/bin/gfortran
already exists. You may want to remove it:
  rm '/usr/local/bin/gfortran'

To force the link and overwrite all conflicting files:
  brew link --overwrite gcc

To list all files that would be deleted:
  brew link --overwrite --dry-run gcc

Possible conflicting files are:
/usr/local/bin/gfortran -> /usr/local/gfortran/bin/gfortran
```

**Comment by pat-s** [comment]
This is related to `gdal`, see [here](https://docs.ropensci.org/tic/articles/ci-providers.html#macos).

Note that we might drop support for Travis in the future (not yet clear) due to their new restrictive policies and because most people already switchted to some other CI provider.

**Comment by alexrecuenco** [comment]
Which other provider do you recommend to switch to then for MacOS and Linux builds

**Comment by pat-s** [comment]
GitHub Actions

**Comment by pat-s** [comment]
@alexrecuenco Did my comment fix your issue?

**Comment by alexrecuenco** [comment]
Yeap, I switched all to GitHub Actions. 


I am not sure if you want to close this, since I haven't addressed the initial issue, but it would be ok with me.

**Comment by pat-s** [comment]
You did not address the issue but I did - you did not test the fix 😄 

The fix works, I know this issue. Closing here then, all the best on GHA :)
