### ISSUE TITLE
error in stage install, "Packaging tic 0.13.0" lazy-load database corrupt ('../R6.rdb')

### ISSUE THREAD

**Issue by philipp-baumann** [ropensci/tic#336]
Hi @pat-s ,

Thanks for the excellent {tic} package. Recently, the {tic} CI for my {opusreader2} package fails for [this PR branch](https://github.com/spectral-cockpit/opusreader2/pull/100) on macOS-latest (release), ubuntu-latest (devel), ubuntu-latest (release), however not on windows-latest (release).

I have restarted the failing CI runs manually, but without success.

For example, [this one](https://github.com/spectral-cockpit/opusreader2/actions/runs/7194760461/job/19596416016?pr=100): 

```r
# ...
✔ Installed pak 0.7.1  (98ms)
ℹ Packaging tic 0.13.2
Error: 
! error in pak subprocess
Caused by error in `zip_data$unzip_class %||% R6::R6Class("unzip_process", inherit = processx::process, …`:
! lazy-load database '/home/runner/work/_temp/Library/pak/library/R6/R/R6.rdb' is corrupt
```

I was wondering, would you have any hint to resolve the issue and why it is suddenly occurring?

Thanks a lot!

Best,
Philipp

**Comment by pat-s** [comment]
I see it in the CI here as well. I hoped it will resolve itself, since it's an issue caused by {pak} as the WF first installs {pak} to install {tic} and since {pak} is a dep of {tic}, {pak} is getting reinstalled and then the two installations collide (for some reason).

```
 pak         0.7.0 → 0.7.0   [bld][cmp][dl] (2.23 MB)
```

This likely results in the lazy-load database error of one of the {pak}'s being installed. I see what I can do.

**Comment by philipp-baumann** [comment]
> I see it in the CI here as well. I hoped it will resolve itself, since it's an issue caused by {pak} as the WF first installs {pak} to install {tic} and since {pak} is a dep of {tic}, {pak} is getting reinstalled and then the two installations collide (for some reason).
> 
> ```
>  pak         0.7.0 → 0.7.0   [bld][cmp][dl] (2.23 MB)
> ```
> 
> This likely results in the lazy-load database error of one of the {pak}'s being installed. I see what I can do.

Thanks Patrick for the super fast diagnostics. I'll try to merge and see if it resolves in the CI run of the main branch.

**Comment by philipp-baumann** [comment]
Surprisingly, it fails again in the main branch after merging this PR: https://github.com/spectral-cockpit/opusreader2/actions/runs/7215190674/job/19659176977

**Comment by philipp-baumann** [comment]
awesome, I just tested your patch and updated the CI template according to your `r-universe` branch. https://github.com/spectral-cockpit/opusreader2/commit/34991759fd403f9412fa3d5fbdab171f4796ab2f Work like a charm, green light. Thanks a lot!

**Comment by philipp-baumann** [comment]
@pat-s FYI I just updated templates using 0.14.0, all working :100: Thanks so much!

**Comment by pat-s** [comment]
Thanks, good to know! It was a bit more work than expected but good to hear it makes people happy 👍
